### ISSUE TITLE
Unable to restore project from database.

### ISSUE THREAD

**Issue by Mayccoll** [directus/app#2617]
Hi all,
Thank you for this great project.
I know you guys  are working on the export and import functionality of a project but I've been struggling with this all day and I haven't been able to know why it happens. I also read many docs and issues.

Sorry if I missing something :worried:

Thank you

# Bug Report

## Steps to Reproduce

1. Install Directus (docker or git install)
2. Create Collections and Fields
3. **STATUS ok** (everything working fine)
4. Create a full database backup (dump database)
5. Create a fresh install (new docker or direct install)
6. Restore the database created in step 4
7. ERRORS Everywhere

## Expected Behavior

Step: 3
3. **STATUS ok** (everything working fine)

## Actual Behavior

- ERROR: `Global Settings` are Empty 
- `Settings > Collection & Fields > Collection' unmanaged fields
- ERROR: `User > Admin` show wrong fields

## Other Context & Screenshots

1.
![Selection_003](https://user-images.githubusercontent.com/2009698/74614845-865c0100-50e9-11ea-900c-eb7be7003a95.png)

2.
![Selection_004](https://user-images.githubusercontent.com/2009698/74614855-9673e080-50e9-11ea-9e3e-41f6db733735.png)

3.
![Selection_005](https://user-images.githubusercontent.com/2009698/74614859-9c69c180-50e9-11ea-87ea-46491bb52395.png)

## Technical Details

- Device: Desktop
- OS: Ubuntu, Centos, Docker
- Web Server: Apache/2.4.29
- PHP Version: 7.2.24
- Database: eg: MySQL 14.14 Distrib 5.7.29
- **Directus** Release Version: **8.5.5**
- Install Method: Cloned, Docker

**Comment by rijkvanzanten** [comment]
When you say 

> Create a full database backup (dump database)

Did you also backup the `directus_` prefixed collections?

**Comment by Mayccoll** [comment]
yes, also directus_ prefidex collections, all tables.

**Comment by rijkvanzanten** [comment]
Can you confirm you're connected to the same database? That all the rows are actually there? The fact that global settings has 0 items indicates that `directus_settings` is empty. The fact that the `manage` buttons show up means that `directus_collections` doesn't have the rows for the collections 🤔

**Comment by Mayccoll** [comment]
Hi, yea same database.
Look this:
1. Docker Install (Directus 1 and Directus 2)
2. Full database "backup" and move to Directus 2 folder
3. Restore database in Directus 2

- Global Settings Empty - Same errors as above 

![Selection_001](https://user-images.githubusercontent.com/2009698/74795753-bdbae100-5294-11ea-9ce0-b967f52c4fe6.png)

**Comment by rijkvanzanten** [comment]
That doesn't make any sense :o 

The only thing I can think of is that maybe the second directus install isn't using the database you're looking at.. or that the tables didn't get moved over correctly (but you already confirmed that)

**Comment by Mayccoll** [comment]
Yea , any sense. i know. And look the ports on the databases, they are 2 totally different instances . 
And that you see in the terminal is what i ran.
Is really easy to recreate. You can do this on the same Docker instance and will break too.

- Step 1.

```yaml
---
version: "3"
services:
  mysql:
    container_name: directus-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "directus"
    ports:
      - "3320:3306"

  directus:
    container_name: directus-app
    image: directus/directus:v8-apache
    ports:
      - "8020:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
    links:
      - mysql:mysql

```

- Step 2

```bash
$ docker-compose up -d
$ docker-compose run directus install --email admin@admin.com --password admin123
```

- Step 3

```sql
mysqldump -u directus -pdirectus -P 3320 -h 0.0.0.0 --single-transaction --max_allowed_packet=512MB --where="true LIMIT 100"  directus > backup-directus.sql
```

- Step 4

```sql
mysql -u directus -pdirectus -P 3320 -h 0.0.0.0 directus < backup-directus.sql
```

- EMPTY SETTINGS
