### ISSUE TITLE
Change body / html height

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#313]
It currently is:

```css
html,
body {
  height: 100%;
}
```

It should be:
```css
html {
  height: 100%;
}

body {
  min-height: 100%;
}
```

That way, the body is still able to scroll naturally
